config/routes.rb
Hnclone::Application.routes.draw do

  resources :comments do
    resources :comments
  end

  resources :votes

  root :to => 'posts#index'

  resources :users
  match '/signup',  to: 'users#new'

  resources :posts do
    resources :comments
  end

  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  get '/:page', to: 'static_pages#show'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body
  has_many :comments, :as => :commentable
  belongs_to :commentable, :polymorphic => true
  has_many :votes, :as => :votable
  belongs_to :user

  def post
    return @post if defined?(@post)
    @post = commentable.is_a?(Post) ? commentable : commentable.post
  end

  def value
    values = 0
      Comment.find(self.id).votes.each { |vote| vote.vote_value ? values += vote.vote_value : values += 0}
    values
  end

   def author
     user = User.find_by_id(self.user_id)
     user.name
   end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :get_parent

  def index
    @comments = Comment.all
  end

  def new
    @comment = @parent.comments.build
  end

  def create
    @comment = @parent.comments.build(params[:comment])
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to post_path(@comment.post), :notice => 'Thank you for your comment!'
    else
      render action: "new"
    end
  end

  def show
    @comment = Comment.find(params[:id])

  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to "www.google.com"
  end

protected

  def get_parent
    @parent = Post.find_by_id(params[:post_id]) if params[:post_id]
    @parent = Comment.find_by_id(params[:comment_id]) if params[:comment_id]
    redirect_to root_path unless defined?(@parent)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<li class="comment">
  <div class="body">
    <%= comment.body %> <br />
    <%= link_to 'Add a Reply', new_comment_comment_path(comment) %>
    <%= pluralize(comment.value,"vote" ) %>
    <%= ( link_to '+1', votes_path(comment_id: comment.id, vote_value: 1), method: :post) %>
    <%= ( link_to '-1', votes_path(comment_id: comment.id, vote_value: -1), method: :post) %>
  </div>

  <%= 'Submitted by: ' %>
  <%= link_to comment.author, user_path %>


  <% unless comment.comments.empty? %>
    <ul class="comment_list">
      <%= render :partial => 'comments/comment', :collection => comment.comments %>
    </ul>
  <% end %>
</li>

app/views/comments/_form.html.erb
<%= form_for [@parent, @comment] do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <br />
    <%= f.text_field :body %>
  </div>

  <div class="actions">
    <%= f.submit "What time is it? Comment time!"%>

  </div>
<% end %>

app/views/comments/index.html.erb
<h1>Listing of all comments</h1>

<table>
  <tr>

    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.body %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Destroy', comment, method: :delete, data:{confirm: 'Are you sure?' }%></td>
  </tr>
<% end %>
</table>

<br />

app/views/comments/new.html.erb
<h1>Comment time!</h1>

 <%= render 'form' %>

 <%= link_to 'Bring me back to XXCombinator, por favor', posts_path %>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

<p id="notice"><%= notice %></p>

<p>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back to home page', posts_path %>