config/routes.rb
Hnclone::Application.routes.draw do

  resources :comments do
    resources :comments
  end

  resources :votes

  root :to => 'posts#index'

  resources :users
  match '/signup',  to: 'users#new'

  resources :posts do
    resources :comments
  end

  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  get '/:page', to: 'static_pages#show'

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :title, :url, :user_id, :posts_by_votes
  has_many :votes, :as => :votable
  has_many :comments, :as => :commentable
  belongs_to :user

  validates_uniqueness_of :url
  validates_presence_of :title, :url
  validates :url, :format => {:with => /(http:\/\/|https:\/\/)/, :message => "Add an http:// or https:// to your URL!"}

  def been_15min?
    @post = Post.find(params[:id])
     (Time.now - @post.created_at) < 900
   end

   def self.random_post
     if (c = count) != 0
       find(:first, :offset =>rand(c))
     end
   end

   def author
     user = User.find_by_id(self.user_id)
     user.name
   end

    def self.ordered_by(param)
       case param
       when 'title'     then Article.order('title')
       when 'published' then Article.order('created_at DESC')
         # length of body - all the spaces from the body = pseudo word count (body + body - spaces)
         # Article.order('LENGTH(body)') <-- small version
       when 'word_count'then Article.order('(LENGTH(body) - (LENGTH(REPLACE(body, " ", "")))) DESC')
       else                  Article.all
     end
   end

   def value
     values = 0
       Post.find(self.id).votes.each { |vote| vote.vote_value ? values += vote.vote_value : values += 0}
     values
   end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
  end

  def edit
    if self.been_15min?
      @post = Post.find(params[:id])
    else
      render action: "show"
    end
  end

  def index
    # Post.order(:vote_count).page
    @posts_sorted = Post.all.sort_by { |post| - post.value}
    @posts_sorted = Kaminari.paginate_array(@posts_sorted).page(params[:page]).per(10)
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  def create
    @post = Post.new(params[:post])
    @post.user_id = current_user.id
      if @post.save
        redirect_to posts_path
      else
        render action: "new"
      end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |p| %>

<% if @post.errors.any? %>
   <div id="error_explanation">
     <h3><%= pluralize(@post.errors.count, "error") %> prohibited this url from being saved:</h3>

        <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
   </div>
 <% end %>

  <div class="field">
    <%= p.label :title %> <br />
    <%= p.text_field :title %>

  </div>

  <div class="field">
    <%= p.label :url %> <br />
    <%= p.text_field :url %>
  </div>

  <div class="actions">
    <%= p.submit %>
  </div>

  <% end %>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

<%= render 'form' %>

<%= link_to 'Show', @post %>
<%= link_to 'Back', posts_path %>

<br /> <%= link_to 'Submit a new Post!', new_post_path %>

app/views/posts/index.html.erb
<h1>Today's Top Posts</h1>
<br />

<table>

  <tr>
    <th>Posts</th>
    <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
    <th>Votes&nbsp;&nbsp;&nbsp;&nbsp;</th>
    <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
    <th>Comments&nbsp;&nbsp;</th>
    <th>Author</th>
  </tr>

  <% @posts_sorted.each do |post| %>
    <tr>
      <td><strong><span style = "font-size: 24px"><%= link_to post.title, post %></span></strong>
      (<%= link_to post.url, post.url %>)</td>
      <td><%= pluralize(post.value,"vote" ) %></td>
      <td><%= button_to '+1',
      votes_path(votable_id: post.id, vote_value: 1), method: :post %></td>
      <td><%= button_to '-1',
      votes_path(votable_id: post.id, vote_value: -1), method: :post %></td>
      <td><%= link_to post.comments.count, post.url %></td>
      <td><%=post.author%></td>
      <% if signed_in? && current_user == post.user %>
      <td><%= link_to 'Edit', edit_post_path(post) %></td>
      <td><%= link_to 'Delete', post, method: :delete, data:{confirm: 'Are you sure?' }%></td>
      <% end %>

    </tr>

  <% end %>
</table>


    <%= paginate @posts_sorted %>


<br /> <b><%= link_to 'Submit a new Post!', new_post_path %></b>
<br />

app/views/posts/new.html.erb
<h1>Put Your New Post Here:</h1>

 <%= render 'form' %>
 <%= link_to 'Take Me Back To All Posts, Por Favor', posts_path %>

app/views/posts/show.html.erb
<p id= "notice"><%= notice %>
<h2> <%= @post.title %> </h2>
<h3> <%= link_to @post.url, @post.url %> </h3>
<%= 'Submitted by: ' %>
<%= @post.author %>
<br />
<br />
<b><p>Comments:</p></b>

<p><%= link_to 'Add a Comment', new_post_comment_path(@post) %></p>

<ul class="comment_list">
  <%= render :partial => 'comments/comment', :collection => @post.comments %>
</ul>

<br />
<b><%= link_to 'Back To All Posts', posts_path %></b>

<br /> <%= link_to 'Submit a BRAND NEW Post!', new_post_path %>