config/routes.rb
Hnclone::Application.routes.draw do

  resources :comments do
    resources :comments
  end

  resources :votes

  root :to => 'posts#index'

  resources :users
  match '/signup',  to: 'users#new'

  resources :posts do
    resources :comments
  end

  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  get '/:page', to: 'static_pages#show'

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "XXcombinator", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", '#' %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", '#' %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Xcombinator" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <!-- IMAGE -->

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <!-- IMAGE -->

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
   <!-- IMAGE -->

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <!-- IMAGE -->



    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <!-- IMAGE -->
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">XXcombinator</a>

          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Why Join?", "/about"  %></li>
               <% if signed_in? %>
                 <li><%= link_to "Sign Out :(", signout_path %></li>
               <% else %>
                 <li><%= link_to "Sign In", signin_path%></li>
                <% end %>
                <% if Post.count > 0 %>
                  <li><%= link_to "Random Post", post_path(Post.random_post)  %></li>
                <% end %>
                <% if signed_in? %>
                 <div class="brand"><%= link_to "Welcome, #{current_user.name}!", current_user %> </div>
                <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
           <div class="span9">
              <% if flash[:error] %>
                <p class='flash notice'>
                  <%= flash[:error] %>
                </p>
              <% end %>
              <%= yield %>
            </div>
            <div class="span3">
              <% if signed_in? %>
               <%= link_to "Sign Me Out :(", signout_path, class: "btn btn-large btn-primary" %>
               <% else %>
               <%= link_to "Sign In To Vote", signin_path, class: "btn btn-large btn-primary" %>
               <br />
               <%= link_to "...or, create an account", signup_path %>
               <% end %>
               <br />

                <br />
                  <%= gravatar_for current_user %>
                <br /><br />

              <div class="well sidebar-nav">
                <h3>Side Dish</h3>

                <ul class="nav nav-list">
                  <!-- <li class="nav-header">In case this page doesn't have enough links for you...</li> -->
                  <% if signed_in? %>
                  <li><%= link_to "My Profile", "#{current_user.id}"  %></li>
                  <li><%= link_to "Submit Post", new_post_path  %></li>
                  <% else %>
                  <li><%= link_to "Why Join Us?", "/about"  %></li>
                  <% end %>
                  <% if Post.count > 0 %>
                    <li><%= link_to "Random Post", post_path(Post.random_post)  %></li>
                  <% end %>
                  <li><%= link_to "Our Fav Post", "/posts/31"  %></li>

                   </ul>
                    </div><!--/.well -->



            </div><!--/span-->
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <p>&copy; JK 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>